{% set name = "orthopy" %}
{% set version = "0.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orthopy-{{ version }}.tar.gz
  sha256: 30c0d4e1c8d26a7edca598eb376bf164e0c872379cca02a2f9a64b3dd2686ccc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - importlib-metadata
    - numpy
    - python >=3.5
    - sympy

test:
  imports:
    - orthopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/orthopy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Orthogonal polynomials in all shapes and sizes.
  description: |
    orthopy provides various orthogonal polynomial classes for 
    lines, triangles, disks, spheres, n-cubes, the nD space with
    weight function exp(-r2) and more. All computations are done
    using numerically stable recurrence schemes. Furthermore, all
    functions are fully vectorized and can return results in exact
    arithmetic.
  doc_url: https://github.com/nschloe/orthopy
  dev_url: https://github.com/nschloe/orthopy

extra:
  recipe-maintainers:
    - jan-janssen
